### ISSUE TITLE
La "stock" apar variatiile produsului cu o eroare

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shopify#1]
In cadrul functiei _ra.sendProductInfo => "inventory", "stock" contine si varietatiile produsului cum ar fi "Size", "Color", "Material", ceea ce rezulta intr-o eroare de tip "Uncaught SyntaxError: Unexpected token-" in Chrome Dev Tools.

Screenshot: http://imgur.com/LvFzxFc

**Comment by cosminatomei** [comment]
done ;)
