### ISSUE TITLE
Illegal string offset 'total_price'

### ISSUE THREAD

**Issue by GabrielCC** [retargeting/Shopify#10]
Error message
E_WARNING: Illegal string offset 'total_price'

Stack trace
in unknown called at /var/www/html/shopify/webhooks/orders/create.php (62)

**Comment by bratucornel** [comment]
Am mai rezolvat doua chestii odata cu asta.
https://github.com/retargeting/Shopify/commit/8822624eeb89a93ed0063813cba90fa69f47f40d
