### ISSUE TITLE
Nu merge saveOrder

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shopify#2]
Evenimentul de saveOrder nu apare in User Journey.

sendProduct si addToCart apar in User Journey.

**Comment by cosminatomei** [comment]
raspunsul la astfel de probleme cu User Journey cel mai bine vine de la voi. si dupa ce imi spuneti ce trebuie schimbat pt ca un eveniment sa fie trimis cu success (this works) si acceptat (this doens't) de server.

**Comment by cosminatomei** [comment]
La teste primesc raspuns de la server:

`_ra.response({"agid": undefined, "sesid": undefined, "email": undefined, "callback": 0, "errors": [], "log": [], "req": "saveOrder"});`

Poate nu tine cont serverul ca e un alt Domeniu (URL) ?
`https://checkout.shopify.com/13559473/checkouts/`

_! Ar trebui sa mearga pe baza de API key.. but you never know_

**Comment by Tynael** [comment]
Da, problema este ca "agid" si "sesid" sunt undefined si de aceea nu ajunge saveOrder-ul in User Journey.

Exista vreo posibilitate sa pastram API Key-ul pe paginile de checkout https://checkout.shopify.com/13559473/checkouts/88bc68c908d6d6043f73460d887bfcf5/thank_you chiar daca este un alt domeniu?

**Comment by cosminatomei** [comment]
Pai se pastreaza:

`
// [...]
ra_key = "CD31G1ZIYHKPSD";
ra_params = {
    add_to_cart_button_id: 'form[action="/cart/add"] [type="submit"]',
    price_label_id: '#price-preview',
};
// [...]
`

Problema e ca server-ul nu cred ca stie sa interpreteze astfel de sesiuni.

**Comment by Tynael** [comment]
Ah, inteleg.

**Comment by GabrielCC** [comment]
Am facut modificarea pe server pentru clienti noi. O sa facem treptat si pentru clienti vechi, care chiar folosesc pluginul. Se poate inchide asta.
