### ISSUE TITLE
Nu merge sendCategory

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shopify#3]
Evenimentul de sendCategory nu apare in User Journey daca utilizatorul acceseaza doar categoriile.

In schimb, sendCategory apare in User Journey daca utiilizatorul a vizionat un produs.

**Comment by cosminatomei** [comment]
voi avea nevoie de mai multe detalii.

Imi poti trimite si un link unde sa pot testa? :)

**Comment by Tynael** [comment]
Ti-am trimis mail :D.

**Comment by cosminatomei** [comment]
Hmm acum am vazut.. nu aveti nici o categorie creata :))

Unde vedeai produsele reprezinta un fel de Root pt toate produsele, nu o categorie (shopify nu o considera categorie si de aceea nu imi returneaza nimic)

Am creat eu o categorie ("[Summer Collection](https://carols-store-2.myshopify.com/collections/summer-collection)") si merge ok:
- se trimite request catre serverul Retargeting
  `_ra.response({"agid": "5784286fd5bc6d24178d9891", "sesid": "5784286fd5bc6d24178d9892", "email": undefined, "callback": 0, "errors": [], "log": [], "req": "sendCategory"});`
