### ISSUE TITLE
addToCart se trimite de 2 ori daca dau 1 singur click

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shopify#4]
Daca dau click pe butonul de Add to Cart, evenimentul addToCart se triggeruieste de 2 ori.

![addtocart](https://cloud.githubusercontent.com/assets/16559614/16757379/46d4b608-4814-11e6-8e5c-3de1d86d3dd1.JPG)

**Comment by cosminatomei** [comment]
ScriptTag-urile au fost adaugate de 2 ori. Can you uninstall and re-install to check again?

**Comment by Tynael** [comment]
Sigur.

**Comment by Tynael** [comment]
Fixed :D !
