### ISSUE TITLE
Nu merg eventurile pe magazine cu domeniu custom

### ISSUE THREAD

**Issue by GabrielCC** [retargeting/Shopify#8]
La Shopify, ai posibilitatea sa iti setezi un domeniu custom.
De exemplu, https://cubio.ro/ este pe shopify.

In momentul in care se fac requesturile de tracking catre retargeting, sunt requesturi care se fac cu variabila shop=shop.shopify.com si requesturi care se fac cu shop=domain.

Cele cu shop=domain nu merg. De exemplu, pentru cubio:
- https://retargeting.biz/shopify/js/triggers.php?shop=cubio-ro.myshopify.com - merge
- https://retargeting.biz/shopify/triggers.php?shop=cubio.ro&t=sendProduct&h=gelatina-bio-vegana-incolora-fara-gluten-6g-biovegan&hc=&v=undefined  - nu merge

2 posibile rezolvari:
- modificat verificarea sa fie facuta in functie de shop sau domain
- modificat js sa tina cont de shop, nu de window.location (adica de domain) (aici https://github.com/retargeting/Shopify/blob/7b3c642aff474fd1428587beaa20ea3f3d5703b1/js/triggers.php#L217)

**Comment by cosminatomei** [comment]
Got it.

**Comment by GabrielCC** [comment]
Poti sa te uiti in jumatate de ora? sau il fac eu acum? Avem vreo 2 clienti care au pluginul instalat degeaba.

**Comment by GabrielCC** [comment]
To late, rezolv eu.

**Comment by GabrielCC** [comment]
@Tynael , poti sa testezi la https://xmade.boutique/ .
Mersi,
Gabriel

**Comment by Tynael** [comment]
@GabrielCC @cosminatomei saveOrder merge la https://xmade.boutique/.

**Comment by GabrielCC** [comment]
Okey, mersi. Il inchidem pe asta.
